package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/vladfc/ghira/internal/graphql/mapper"
	"github.com/vladfc/ghira/internal/graphql/model"
	"github.com/vladfc/ghira/internal/user"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetUsers(ctx)
	if err != nil {
		return nil, err
	}

	return mapper.UsersToGraphQL(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	foundUser, err := r.UserService.GetUserByID(ctx, id)
	if err != nil {
		if errors.Is(err, user.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	if foundUser == nil {
		return nil, nil
	}

	return mapper.UserToGraphQL(*foundUser), nil
}
